#!/usr/bin/env bash

CUR_DATE=`date +%Y-%m-%d`
CUR_DIR=`pwd`

function usage {
    echo "ERROR: $0 <blog entry file name>";
    exit 1;
}

if [ $1 ]; then
    ACTION=$1
else
    usage
fi

hugo new posts/${CUR_DATE}-${1}.md -v